otaku:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: otaku_store
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-hongkong.aliyuncs.com
    access-key-id: LTAI5t6nuwDLaLTUYarGGjbL
    access-key-secret: aGU6GEqp3JDASD5g1qE44qEuz46DUw
    bucket-name: otakustore

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0

  wechat:
    appid:
    secret:
    mchid:
    mchSerialNo:
    privateKeyFilePath:
    apiV3Key:
    weChatPayCertFilePath:
    notifyUrl:
    refundNotifyUrl: