server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${otaku.datasource.driver-class-name}
      url: jdbc:mysql://${otaku.datasource.host}:${otaku.datasource.port}/${otaku.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${otaku.datasource.username}
      password: ${otaku.datasource.password}
  redis:
    host: ${otaku.redis.host}
    port: ${otaku.redis.port}
    #password: ${otaku.redis.password}}
    database: ${otaku.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.otaku.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      otaku:
        mapper: debug
        service: info
        controller: info

otaku:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: otaku
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: otakuStore
    # 设置jwt过期时间
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称
    user-token-name: authentication

  alioss:
    endpoint: ${otaku.alioss.endpoint}
    access-key-id: ${otaku.alioss.access-key-id}
    access-key-secret: ${otaku.alioss.access-key-secret}
    bucket-name: ${otaku.alioss.bucket-name}

  wechat:
    appid: ${otaku.wechat.appid}
    secret: ${otaku.wechat.secret}
